package main

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"go.mau.fi/whatsmeow"
	waProto "go.mau.fi/whatsmeow/binary/proto"
	"go.mau.fi/whatsmeow/types/events"
	"google.golang.org/protobuf/proto"
)

// ==========================================
// 🍪 1. COOKIE MANAGEMENT
// ==========================================

type CookieJSON struct {
	Name   string `json:"name"`
	Value  string `json:"value"`
	Domain string `json:"domain"`
	Path   string `json:"path"`
}

var rawCookieHeader string

// loadCookies reads the Youtube_cookies.json file generated by browser extensions
func loadCookies(filename string) {
	file, err := os.Open(filename)
	if err != nil {
		fmt.Println("⚠️ [WARNING] Cookies file not found:", err)
		return
	}
	defer file.Close()

	var rawCookies []CookieJSON
	err = json.NewDecoder(file).Decode(&rawCookies)
	if err != nil {
		fmt.Println("⚠️ [ERROR] Error decoding cookies JSON:", err)
		return
	}

	var parts []string
	hasConsent := false
	youtubeCookiesCount := 0

	for _, c := range rawCookies {
		// Filter out non-YouTube garbage cookies
		if !strings.Contains(c.Domain, "youtube.com") {
			continue
		}

		cleanValue := strings.ReplaceAll(c.Value, "\n", "")
		cleanValue = strings.ReplaceAll(cleanValue, "\r", "")
		parts = append(parts, fmt.Sprintf("%s=%s", c.Name, cleanValue))
		
		youtubeCookiesCount++

		if strings.ToUpper(c.Name) == "CONSENT" {
			hasConsent = true
		}
	}
	
	// Auto-add CONSENT cookie to bypass YouTube terms page if missing
	if !hasConsent {
		parts = append(parts, "CONSENT=YES+cb.20210328-17-p0.en+FX+478")
		youtubeCookiesCount++
	}
	
	rawCookieHeader = strings.Join(parts, "; ")
	fmt.Printf("🍪 Loaded %d strictly YouTube cookies from %s successfully!\n", youtubeCookiesCount, filename)
}

// ==========================================
// 🚀 2. DOWNLOAD HELPER
// ==========================================

func downloadMediaDirect(filepath string, targetURL string, rawCookies string) error {
	req, err := http.NewRequest("GET", targetURL, nil)
	if err != nil {
		return err
	}
	
	// Strict Android Headers to bypass Anti-Bot
	req.Header.Set("User-Agent", "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Mobile Safari/537.36")
	req.Header.Set("Accept-Language", "en-US,en;q=0.9")
	req.Header.Set("Sec-Ch-Ua-Platform", "\"Android\"")
	req.Header.Set("Sec-Ch-Ua-Mobile", "?1")
	
	if rawCookies != "" {
		req.Header.Set("Cookie", rawCookies)
	}

	client := &http.Client{Timeout: 5 * time.Minute}
	resp, err := client.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	out, err := os.Create(filepath)
	if err != nil {
		return err
	}
	defer out.Close()

	_, err = io.Copy(out, resp.Body)
	return err
}

// ==========================================
// 🎯 3. MAIN DIRECT DOWNLOAD HANDLER
// ==========================================

func handleAPIDownload(client *whatsmeow.Client, v *events.Message, videoURL string) {
	if videoURL == "" {
		replyMessage(client, v, "❌ *Error:* Please provide a valid link!\n*Example:* `.hindidwn https://youtu.be/xxxx`")
		return
	}

	react(client, v, "⏳") 
	replyMessage(client, v, "⏳ Processing video with active cookies...")

	// Create temporary directory for processing and error dumps
	tempDir, err := os.MkdirTemp("", "ytbot_hindi_*")
	if err != nil {
		replyMessage(client, v, "❌ *System Error:* Failed to create temp directory.")
		return
	}
	defer os.RemoveAll(tempDir) 

	// 🛠️ Dynamic Error Dumper for Debugging
	dumpAndSendError := func(errorMsg string, rawData string) {
		react(client, v, "⚠️")
		replyMessage(client, v, fmt.Sprintf("⚠️ *Extraction Failed:* %s\n📥 Sending raw data dump for debugging...", errorMsg))
		
		dumpFileName := fmt.Sprintf("Error_Dump_%d.txt", time.Now().UnixNano())
		dumpFilePath := filepath.Join(tempDir, dumpFileName)
		
		os.WriteFile(dumpFilePath, []byte(rawData), 0644)
		
		fileData, err := os.ReadFile(dumpFilePath)
		if err == nil {
			uploadResp, err := client.Upload(context.Background(), fileData, whatsmeow.MediaDocument)
			if err == nil {
				msg := &waProto.Message{
					DocumentMessage: &waProto.DocumentMessage{
						URL:           proto.String(uploadResp.URL),
						DirectPath:    proto.String(uploadResp.DirectPath),
						MediaKey:      uploadResp.MediaKey,
						Mimetype:      proto.String("text/plain"),
						FileName:      proto.String(dumpFileName),
						Caption:       proto.String("📋 YouTube Raw Response Dump"),
						FileLength:    proto.Uint64(uint64(len(fileData))),
						FileSHA256:    uploadResp.FileSHA256,
						FileEncSHA256: uploadResp.FileEncSHA256,
					},
				}
				client.SendMessage(context.Background(), v.Info.Chat, msg)
			}
		}
	}

	// Extract Video ID
	videoID := ""
	if strings.Contains(videoURL, "v=") {
		parts := strings.Split(videoURL, "v=")
		videoID = strings.Split(parts[1], "&")[0]
	} else if strings.Contains(videoURL, "youtu.be/") {
		parts := strings.Split(videoURL, "youtu.be/")
		videoID = strings.Split(parts[1], "?")[0]
	} else {
		videoID = strings.TrimSpace(videoURL)
	}

	targetURL := "https://m.youtube.com/watch?v=" + videoID

	req, _ := http.NewRequest("GET", targetURL, nil)
	req.Header.Set("User-Agent", "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Mobile Safari/537.36")
	req.Header.Set("Accept-Language", "en-US,en;q=0.9")
	req.Header.Set("Sec-Ch-Ua-Platform", "\"Android\"")
	req.Header.Set("Sec-Ch-Ua-Mobile", "?1")
	
	if rawCookieHeader != "" {
		req.Header.Set("Cookie", rawCookieHeader)
	} else {
		fmt.Println("⚠️ [WARNING] rawCookieHeader is empty. Proceeding without cookies.")
	}

	httpClient := &http.Client{Timeout: 15 * time.Second}
	resp, err := httpClient.Do(req)
	if err != nil {
		replyMessage(client, v, "❌ *Network Error:* Failed to connect to YouTube.")
		return
	}
	defer resp.Body.Close()

	bodyBytes, _ := io.ReadAll(resp.Body)
	bodyString := string(bodyBytes)

	// Check if cookies were rejected
	if strings.Contains(bodyString, "problem with your cookie settings") {
		dumpAndSendError("Google rejected the cookies (Cookies might be expired).", bodyString)
		return
	}

	// Extract JSON Data using Regex
	re := regexp.MustCompile(`(?s)ytInitialPlayerResponse\s*=\s*(\{.+?\});(?:var\s|</script>)`)
	match := re.FindStringSubmatch(bodyString)
	if len(match) < 2 {
		dumpAndSendError("Video JSON data not found! YouTube page structure might have changed or bot is blocked.", bodyString)
		return
	}

	var playerData map[string]interface{}
	err = json.Unmarshal([]byte(match[1]), &playerData)
	if err != nil {
		dumpAndSendError("Failed to parse JSON data.", match[1])
		return
	}

	// Check Playability Status
	if playability, ok := playerData["playabilityStatus"].(map[string]interface{}); ok {
		if status, _ := playability["status"].(string); status != "OK" {
			reason, _ := playability["reason"].(string)
			dumpAndSendError(fmt.Sprintf("Video cannot be played: %s", reason), match[1])
			return
		}
	}

	streamingData, ok := playerData["streamingData"].(map[string]interface{})
	if !ok {
		dumpAndSendError("StreamingData object is missing.", match[1])
		return
	}

	var bestVideoURL, hindiAudioURL, defaultAudioURL string

	// Parse Adaptive Formats
	if adaptiveFormats, ok := streamingData["adaptiveFormats"].([]interface{}); ok {
		for _, f := range adaptiveFormats {
			fmtData, ok := f.(map[string]interface{})
			if !ok { continue }

			mime, _ := fmtData["mimeType"].(string)
			url, _ := fmtData["url"].(string)
			if url == "" { continue }

			// 1. Find 360p Video
			if strings.Contains(mime, "video/mp4") && bestVideoURL == "" {
				quality, _ := fmtData["qualityLabel"].(string)
				if quality == "360p" || quality == "360p60" {
					bestVideoURL = url
				}
			}

			// 2. Find Audio (Hindi preferred)
			if strings.Contains(mime, "audio/") {
				if strings.Contains(url, "lang%3Dhi") || strings.Contains(url, "lang=hi") {
					hindiAudioURL = url
				} else if defaultAudioURL == "" && !strings.Contains(url, "dubbed") {
					defaultAudioURL = url
				}
			}
		}
	}

	if bestVideoURL == "" {
		dumpAndSendError("Direct 360p MP4 link not found (Cipher signature might be active).", match[1])
		return
	}

	finalAudioURL := hindiAudioURL
	audioMode := "Hindi Dubbed"
	if finalAudioURL == "" {
		finalAudioURL = defaultAudioURL
		audioMode = "Original Audio"
	}

	vidPath := filepath.Join(tempDir, "video.mp4")
	audPath := filepath.Join(tempDir, "audio.m4a")
	outPath := filepath.Join(tempDir, "final.mp4")

	react(client, v, "📥")
	replyMessage(client, v, fmt.Sprintf("⏳ Links extracted! Downloading and merging with %s...", audioMode))

	// Download Video and Audio
	err = downloadMediaDirect(vidPath, bestVideoURL, rawCookieHeader)
	if err != nil {
		replyMessage(client, v, "❌ *Download Error:* Failed to fetch video stream.")
		return
	}
	
	err = downloadMediaDirect(audPath, finalAudioURL, rawCookieHeader)
	if err != nil {
		replyMessage(client, v, "❌ *Download Error:* Failed to fetch audio stream.")
		return
	}

	react(client, v, "🔄")

	// 🔥 FFmpeg Magic: -movflags +faststart makes it playable inside WhatsApp
	cmd := exec.Command("ffmpeg", "-y", 
		"-i", vidPath, 
		"-i", audPath, 
		"-c:v", "copy",       
		"-c:a", "aac",        
		"-movflags", "+faststart", 
		outPath,
	)
	
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	err = cmd.Run()
	if err != nil {
		dumpAndSendError("FFmpeg merging process failed.", stderr.String())
		return
	}

	react(client, v, "📤")

	// Trigger existing upload function
	title := fmt.Sprintf("YouTube Video (%s)", audioMode)
	uploadAndSendFile(client, v, outPath, title, false, 1, 1)
	
	react(client, v, "✅")
}
